pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                sh 'echo "Building docker images"'
            }
        }
        stage('Test'){
            steps{
                sh 'echo "Testing docker images"'
            }
        }
        stage('Deploy'){
            steps{
                sh 'echo "Deploying docker images"'
            }
        }
    }
}
