pipeline{
    agent{
        label 'Dev'
    }
    stages{
        stage('Build'){
            steps{
                sh 'echo "Building docker image"'
            }
        }
        stage('Test'){
            steps{
                sh 'echo "Testing docker image"'
            }
        }
        stage('Deploy'){
            steps{
                sh 'echo "Deploying docker image"'
            }
        }
    }
}
